name: mindisle_client
description: "基于 Flutter 的心岛心理健康管理应用：通过 AI 辅助的用药管理、体重与副作用监测、情绪与量表评估，帮助患者与医生实现安全、持续的心理健康管理。"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  launcher_name: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.4.7
  hive_ce_flutter: ^2.3.1
  logger: ^2.6.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/icon/app_icon_foreground.png
    - assets/icon/app_icon_background.png

flutter_launcher_icons:
  android: true
  ios: true

  image_path: assets/icon/app_icon.png

  adaptive_icon_foreground: assets/icon/app_icon_foreground.png
  adaptive_icon_background: assets/icon/app_icon_background.png


  remove_alpha_ios: true

launcher_name:
  default: "Mind Isle"
  zh-rCN: "心·岛"
  zh-rTW: "心·島"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon_foreground.png
  android: true
  ios: true

  android_12:
    color: "#ffffff"
    image: assets/icon/app_icon_foreground.png
